# Generated by Django 5.0.7 on 2025-07-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_employee_address_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='ai_analysis_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='career',
            name='ai_concerns',
            field=models.TextField(blank=True, help_text='AI identified potential concerns', null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='ai_education_match',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Education alignment score (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='ai_experience_match',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Experience alignment score (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='ai_match_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI calculated match score (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='ai_recommendation',
            field=models.CharField(blank=True, choices=[('highly_recommended', 'Highly Recommended'), ('recommended', 'Recommended'), ('consider', 'Consider'), ('not_recommended', 'Not Recommended')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='ai_skills_match',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Skills alignment score (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='ai_strengths',
            field=models.TextField(blank=True, help_text='AI identified candidate strengths', null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI generated summary of the candidate', null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Extracted text from resume', null=True),
        ),
    ]
