# Generated by Django 5.0.7 on 2025-07-19 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_filedocument_fileactivity_filefolder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('share', 'Share'), ('edit', 'Edit'), ('view', 'View'), ('delete', 'Delete'), ('archive', 'Archive'), ('member_add', 'Member Added'), ('member_remove', 'Member Removed')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pages.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit'), ('admin', 'Admin')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='pages.board')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_board_shares', to='pages.employee')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_board_shares', to='pages.employee')),
            ],
            options={
                'unique_together': {('board', 'shared_with')},
            },
        ),
    ]
