# Generated by Django 5.0.7 on 2025-07-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_boardactivity_boardshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='storage_quota',
            field=models.BigIntegerField(blank=True, help_text='Storage quota in bytes', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='storage_used',
            field=models.BigIntegerField(default=0, help_text='Storage used in bytes'),
        ),
    ]
