# Generated by Django 5.0.7 on 2025-07-20 04:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_storageallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_completed', models.BooleanField(default=False)),
                ('analysis_started_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='AI-determined category', max_length=100)),
                ('key_topics', models.JSONField(default=list, help_text='Extracted key topics')),
                ('entities', models.JSONField(default=list, help_text='Named entities found')),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment analysis score (-1 to 1)', null=True)),
                ('sentiment_label', models.CharField(blank=True, help_text='Sentiment label', max_length=20)),
                ('readability_score', models.FloatField(blank=True, help_text='Readability score', null=True)),
                ('complexity_score', models.FloatField(blank=True, help_text='Content complexity score', null=True)),
                ('quality_score', models.FloatField(blank=True, help_text='Overall quality score', null=True)),
                ('contains_sensitive_info', models.BooleanField(default=False)),
                ('sensitive_info_types', models.JSONField(default=list, help_text='Types of sensitive information found')),
                ('security_risk_level', models.CharField(default='low', help_text='Security risk assessment', max_length=20)),
                ('has_images', models.BooleanField(default=False)),
                ('has_tables', models.BooleanField(default=False)),
                ('has_links', models.BooleanField(default=False)),
                ('ai_recommendations', models.JSONField(default=list, help_text='AI-generated recommendations')),
                ('suggested_tags', models.JSONField(default=list, help_text='AI-suggested tags')),
                ('suggested_category', models.CharField(blank=True, max_length=100)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='pages.filedocument')),
            ],
            options={
                'ordering': ['-analysis_started_at'],
            },
        ),
        migrations.CreateModel(
            name='AINotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(default='22:00')),
                ('quiet_hours_end', models.TimeField(default='08:00')),
                ('priority_threshold', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Minimum priority level for notifications', max_length=10)),
                ('security_notifications', models.BooleanField(default=True)),
                ('storage_notifications', models.BooleanField(default=True)),
                ('collaboration_notifications', models.BooleanField(default=True)),
                ('duplicate_notifications', models.BooleanField(default=False)),
                ('quality_notifications', models.BooleanField(default=False)),
                ('file_management_notifications', models.BooleanField(default=True)),
                ('workflow_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='pages.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AIWorkflowRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('file_upload', 'File Upload'), ('file_modified', 'File Modified'), ('file_shared', 'File Shared'), ('schedule_based', 'Schedule Based'), ('threshold_reached', 'Threshold Reached'), ('user_action', 'User Action'), ('time_based', 'Time Based')], max_length=20)),
                ('conditions', models.JSONField(default=dict, help_text='Workflow conditions as JSON')),
                ('actions', models.JSONField(default=list, help_text='Workflow actions as JSON')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflows', to='pages.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIWorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('context_data', models.JSONField(default=dict, help_text='Execution context data')),
                ('result_data', models.JSONField(default=dict, help_text='Execution results')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executions', to='pages.filedocument')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_workflows', to='pages.employee')),
                ('workflow_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pages.aiworkflowrule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AINotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('security', 'Security'), ('storage_management', 'Storage Management'), ('collaboration', 'Collaboration'), ('duplicate_detection', 'Duplicate Detection'), ('content_quality', 'Content Quality'), ('file_management', 'File Management'), ('workflow', 'Workflow'), ('general', 'General')], default='general', max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Additional notification data')),
                ('is_read', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pages.filedocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_notifications', to='pages.employee')),
                ('workflow_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pages.aiworkflowexecution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='pages_ainot_user_id_fc2c5c_idx'), models.Index(fields=['priority', 'created_at'], name='pages_ainot_priorit_57650d_idx')],
            },
        ),
    ]
