# Generated by Django 5.0.7 on 2025-07-20 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_add_ai_workflow_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifileanalysis',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='aifileanalysis',
            name='priority',
            field=models.IntegerField(default=5, help_text='Processing priority (1=highest, 10=lowest)'),
        ),
        migrations.AddField(
            model_name='aifileanalysis',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aifileanalysis',
            name='queued_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aifileanalysis',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aifileanalysis',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='queued', max_length=20),
        ),
    ]
