# Generated by Django 5.0.7 on 2025-07-20 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_chatchannel_chatchannelmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatchannel',
            name='associated_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_channels', to='pages.board'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='shared_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='pages.board'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='shared_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='pages.filedocument'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='channel_type',
            field=models.CharField(choices=[('general', 'General'), ('department', 'Department'), ('project', 'Project'), ('board', 'Board Discussion'), ('private', 'Private Group')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('board', 'Board Share'), ('system', 'System')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatnotification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('mention', 'Mentioned'), ('channel_invite', 'Channel Invite'), ('board_shared', 'Board Shared'), ('file_shared', 'File Shared')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChatFileShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_type', models.CharField(choices=[('message', 'Shared in Message'), ('channel', 'Shared to Channel')], default='message', max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('share_message', models.TextField(blank=True, help_text='Optional message when sharing the file')),
                ('download_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='pages.chatchannel')),
                ('file_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_shares', to='pages.filedocument')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='pages.chatmessage')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files_in_chat', to='pages.employee')),
            ],
            options={
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatBoardShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, help_text='Optional message when sharing the board')),
                ('is_active', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_shares', to='pages.board')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_boards', to='pages.chatchannel')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_boards_in_chat', to='pages.employee')),
            ],
            options={
                'ordering': ['-shared_at'],
                'unique_together': {('channel', 'board')},
            },
        ),
    ]
