# Generated by Django 5.0.7 on 2025-07-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_chatchannel_associated_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifileanalysis',
            name='analysis_data',
            field=models.JSONField(default=dict, help_text='Complete analysis results and metadata'),
        ),
        migrations.AddField(
            model_name='aifileanalysis',
            name='tags',
            field=models.JSONField(default=list, help_text='Generated tags for the file'),
        ),
    ]
