# Generated by Django 5.0.7 on 2025-09-19 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_add_analysis_data_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Form title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Form description')),
                ('form_fields', models.JSONField(default=dict, help_text='Form field configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pin_expiry_hours', models.IntegerField(default=48, help_text='PIN expiry time in hours')),
                ('allow_multiple_submissions', models.BooleanField(default=False)),
                ('send_confirmation_email', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_onboarding_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('custom_message', models.TextField(blank=True, help_text='Custom message for the invitation')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='sent', max_length=20)),
                ('first_opened', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('onboarding_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.onboardingform')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_onboarding_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_data', models.JSONField(default=dict, help_text='Submitted form data')),
                ('uploaded_files', models.JSONField(default=list, help_text='List of uploaded file paths')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('hr_notes', models.TextField(blank=True, help_text='Internal HR notes')),
                ('next_steps', models.TextField(blank=True, help_text='Next steps in the process')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.onboardinginvitation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectiveEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('current_pin', models.CharField(blank=True, max_length=6)),
                ('pin_created_at', models.DateTimeField(blank=True, null=True)),
                ('pin_expiry', models.DateTimeField(blank=True, null=True)),
                ('pin_attempts', models.IntegerField(default=0)),
                ('is_pin_locked', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_prospects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='onboardinginvitation',
            name='prospective_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.prospectiveemployee'),
        ),
        migrations.CreateModel(
            name='OnboardingFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('email', 'Email'), ('phone', 'Phone Number'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown Select'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('file', 'File Upload'), ('signature', 'Digital Signature')], max_length=20)),
                ('field_name', models.CharField(help_text='Internal field name', max_length=100)),
                ('field_label', models.CharField(help_text='Display label', max_length=200)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('validation_regex', models.CharField(blank=True, help_text='Regex pattern for validation', max_length=500)),
                ('field_options', models.JSONField(default=list, help_text='Options for select/radio/checkbox fields')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('onboarding_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='pages.onboardingform')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('onboarding_form', 'field_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='onboardinginvitation',
            unique_together={('onboarding_form', 'prospective_employee')},
        ),
    ]
