# Generated by Django 5.2.6 on 2025-10-06 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_onboardingform_onboardinginvitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('ssn', models.CharField(blank=True, help_text='Format: XXX-XX-XXXX', max_length=11)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('filing_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married_joint', 'Married Filing Jointly'), ('married_separate', 'Married Filing Separately'), ('head_of_household', 'Head of Household'), ('qualifying_widow', 'Qualifying Widow(er)')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('current_pin', models.CharField(blank=True, help_text='PIN for secure access', max_length=10)),
                ('pin_expiry', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TaxFormAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('custom_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision')], default='assigned', max_length=20)),
                ('first_accessed', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.taxclient')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_data', models.JSONField(default=dict, help_text='Submitted form field values')),
                ('uploaded_files', models.JSONField(default=list, help_text='List of uploaded file paths')),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded signature image')),
                ('signature_file_path', models.CharField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('preparer_notes', models.TextField(blank=True, help_text='Internal notes for tax preparer')),
                ('estimated_refund', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_owed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.taxformassignment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('w2', 'W-2 Form'), ('1099', '1099 Form'), ('1098', '1098 Form'), ('photo_id', 'Photo ID'), ('voided_check', 'Voided Check'), ('receipt', 'Receipt/Expense'), ('bank_statement', 'Bank Statement'), ('other', 'Other Document')], max_length=50)),
                ('file_name', models.CharField(max_length=300)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pages.taxformsubmission')),
            ],
            options={
                'ordering': ['document_type', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Form name (e.g., 'Tax Intake Form')", max_length=200)),
                ('form_type', models.CharField(choices=[('intake', 'Tax Intake Form'), ('schedule_c', 'Schedule C - Business Income'), ('schedule_a', 'Schedule A - Itemized Deductions'), ('income_summary', 'Income Summary'), ('dependent_care', 'Dependent Care Form'), ('student_ack', 'Student Acknowledgment'), ('photo_id', 'Photo ID and Voided Check'), ('due_diligence', 'Due Diligence Questionnaire'), ('refund_type', 'Refund Type Selection'), ('affordable_care', 'Affordable Care Details'), ('custom', 'Custom Form')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Instructions for filling out the form')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_signature', models.BooleanField(default=True)),
                ('allow_multiple_submissions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tax_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['form_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='taxformassignment',
            name='tax_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.taxformtemplate'),
        ),
        migrations.CreateModel(
            name='TaxFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('email', 'Email'), ('phone', 'Phone Number'), ('number', 'Number'), ('currency', 'Currency ($)'), ('date', 'Date'), ('select', 'Select Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('file', 'File Upload'), ('signature', 'Digital Signature'), ('ssn', 'Social Security Number'), ('ein', 'Employer ID Number'), ('address', 'Address Block'), ('name', 'Full Name'), ('section_header', 'Section Header'), ('table', 'Data Table'), ('yes_no', 'Yes/No Radio')], max_length=20)),
                ('field_name', models.CharField(help_text='Internal field name', max_length=100)),
                ('field_label', models.CharField(help_text='Display label', max_length=300)),
                ('placeholder', models.CharField(blank=True, max_length=300)),
                ('help_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('validation_regex', models.CharField(blank=True, max_length=500)),
                ('field_options', models.JSONField(default=list, help_text='Options for select/radio/checkbox fields')),
                ('section', models.CharField(blank=True, help_text='Section name for grouping', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order within section')),
                ('column_width', models.CharField(choices=[('full', 'Full Width'), ('half', 'Half Width'), ('third', 'Third Width'), ('quarter', 'Quarter Width')], default='full', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_line_reference', models.CharField(blank=True, help_text='IRS form line reference', max_length=100)),
                ('is_calculated', models.BooleanField(default=False, help_text='Is this field auto-calculated?')),
                ('calculation_formula', models.TextField(blank=True, help_text='Formula for calculated fields')),
                ('tax_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='pages.taxformtemplate')),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
                'unique_together': {('tax_form', 'field_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='taxformassignment',
            unique_together={('tax_form', 'client')},
        ),
    ]
