# Generated by Django 5.2.6 on 2025-10-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_taxclient_taxformassignment_taxformsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxclient',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this client'),
        ),
    ]
