# Generated by Django 5.2.6 on 2025-10-06 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_taxclient_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxformsubmission',
            name='client_signature_data',
            field=models.TextField(blank=True, help_text='Base64 encoded client signature image'),
        ),
        migrations.AddField(
            model_name='taxformsubmission',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, help_text='When client signed the form', null=True),
        ),
        migrations.AddField(
            model_name='taxformsubmission',
            name='employee_completed_at',
            field=models.DateTimeField(blank=True, help_text='When employee completed the form', null=True),
        ),
        migrations.AddField(
            model_name='taxformsubmission',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes from employee'),
        ),
        migrations.AddField(
            model_name='taxformsubmission',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True when both employee filled and client signed'),
        ),
        migrations.AddField(
            model_name='taxformsubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Employee who filled the form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_submissions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxformassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('ready_for_signature', 'Ready for Client Signature'), ('completed', 'Completed'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxformsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_submissions_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxformsubmission',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image (legacy)'),
        ),
    ]
