# Generated by Django 5.2.6 on 2025-10-09 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_add_two_step_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxClientWaiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waiver_version', models.CharField(default='1.0', help_text='Version of waiver terms', max_length=20)),
                ('client_signed', models.BooleanField(default=False)),
                ('client_signature_data', models.TextField(blank=True, help_text='Base64 signature image data')),
                ('client_signed_at', models.DateTimeField(blank=True, null=True)),
                ('client_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('employee_witnessed', models.BooleanField(default=False)),
                ('witnessed_at', models.DateTimeField(blank=True, null=True)),
                ('consent_data_processing', models.BooleanField(default=False, help_text='Consent to process tax data')),
                ('consent_document_storage', models.BooleanField(default=False, help_text='Consent to store documents')),
                ('consent_electronic_delivery', models.BooleanField(default=False, help_text='Consent to electronic document delivery')),
                ('consent_third_party_disclosure', models.BooleanField(default=False, help_text='Consent for IRS/state communications')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about waiver')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiver', to='pages.taxclient')),
                ('witnessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_waivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
