# Generated by Django 5.2.6 on 2025-10-27 17:45

import django.db.models.deletion
import pages.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_onboardingofferletter_job_posting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingPDFForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_file', models.FileField(upload_to=pages.models.onboarding_pdf_template_upload_path)),
                ('default_instructions', models.TextField(blank=True, help_text='Guidance shown to prospects when completing this PDF.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_pdf_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingPDFTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('custom_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting Upload'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('completed_file', models.FileField(blank=True, null=True, upload_to=pages.models.onboarding_pdf_submission_upload_path)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboarding_pdf_tasks', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_tasks', to='pages.onboardinginvitation')),
                ('pdf_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.onboardingpdfform')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboarding_pdf_tasks', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_onboarding_pdf_tasks', to='pages.prospectiveemployee')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('pdf_form', 'invitation')},
            },
        ),
    ]
