# Generated by Django 5.2.6 on 2025-10-30 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_onboardingpdfform_onboardingpdftask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_timed', models.BooleanField(default=False, help_text='If true, candidates have a time limit to complete the assessment')),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Time limit in minutes when timed', null=True)),
                ('allow_multiple_attempts', models.BooleanField(default=False)),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, help_text='Optional passing score (percentage)', max_digits=5, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_onboarding_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='onboardinginvitation',
            name='assessments',
            field=models.ManyToManyField(blank=True, related_name='invitations', to='pages.onboardingassessment'),
        ),
        migrations.CreateModel(
            name='OnboardingAssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Total points earned', max_digits=7, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score', max_digits=5, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='pages.onboardingassessment')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='pages.onboardinginvitation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingAssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('open', 'Open Ended')], default='open', max_length=10)),
                ('choices', models.JSONField(blank=True, default=list, help_text='Choice options for MCQ questions')),
                ('correct_answer', models.JSONField(blank=True, help_text='Index or list of indices indicating correct choice(s)', null=True)),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pages.onboardingassessment')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingAssessmentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('points_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='pages.onboardingassessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.onboardingassessmentquestion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
